version: 2
jobs:
   build:
     working_directory: ~/code
     docker:
       - image: circleci/android:api-26-alpha
     environment:
       JVM_OPTS: -Xmx2048m
       GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
     steps:
       - checkout
       - run:
           name: Setup emulator
           command: sdkmanager "system-images;android-24;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-24;default;armeabi-v7a"
       - run:
           name: Launch emulator
           command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -skin "768x1280" -noaudio -no-boot-anim -no-window -accel off -logcat *:e
           background: true
           parallel: true
       - run:
           name: Wait for emulator
           command: circle-android wait-for-boot && sleep 70
       - run:
           name: Disable emulator animations
           command: |
              adb shell settings put global window_animation_scale 0.0
              adb shell settings put global transition_animation_scale 0.0
              adb shell settings put global animator_duration_scale 0.0
              adb shell settings put secure show_ime_with_hard_keyboard 0
              adb shell input keyevent 82
       - run:
           name: Compile App
           command: ./gradlew assembleDebug
       - run:
           name: Install App
           command: adb install -g /home/circleci/code/build/outputs/apk/debug/code-debug.apk
       - run:
           name: Run Tests
           command: ./gradlew connectedAndroidTest -PdisablePreDex  --stacktrace 
           no_output_timeout: 3600
       - run:
           name: Run Lint
           command: ./gradlew lint
       - store_artifacts:
           path: build/reports
           destination: reports
       - store_test_results:
           path: build/reports/androidTests
       - store_test_results:
           path: build/reports/tests