version: 2
jobs:
   build:
     working_directory: ~/code
     docker:
       - image: circleci/android:api-26-alpha
     environment:
       JVM_OPTS: -Xmx2048m
       GRADLE_OPTS: -Dorg.gradle.jvmargs="-Xmx2048m -XX:+HeapDumpOnOutOfMemoryError"
     steps:
       - checkout
       - run:
           name: Install tools
           command: |
              sudo apt-get install -y gcc python-dev python-setuptools
              sudo easy_install -U pip
              sudo pip uninstall -y crcmod
              sudo pip install -U crcmod
       - run:
           name: Install GCloud
           command: |
              echo "deb http://packages.cloud.google.com/apt cloud-sdk-$(lsb_release -c -s) main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
              curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
              cat /etc/apt/sources.list.d/google-cloud-sdk.list
              sudo apt-get update && sudo apt-get install -y google-cloud-sdk
       - run:
           name: Configure Google Cloud Access
           command: |
              wget "https://drive.google.com/uc?export=download&id=${GCLOUD_SERVICE_ACCOUNT_SECRETS_FILE_ID}" -O ${HOME}/client-secret.json
              echo $GCLOUD_SERVICE_KEY | base64 --decode > ${HOME}/client-secret.json
              sudo gcloud config set project ${GCLOUD_PROJECT}
              sudo gcloud --quiet components update
              sudo gcloud --quiet components install beta
              sudo gcloud auth activate-service-account ${GCLOUD_SERVICE_ACCOUNT} --key-file ${HOME}/client-secret.json
       - run:
           name: Lint
           command: ./gradlew lint
       - run:
           name: Generate Debug APK
           command: ./gradlew assembleDebug -PdisablePreDex
       - run:
           name: Generate Debug Testing APK
           command: ./gradlew assembleDebugAndroidTest -PdisablePreDex
       - store_artifacts:
           path: build/reports
           destination: reports
       - store_test_results:
           path: build/reports/androidTests
       - store_test_results:
           path: build/reports/tests